generatorName: php
typeMappings:
  "object": "array"
additionalProperties:
  packageName: dropbox/sign
  packageVersion: "^1.0.0"
  artifactVersion: 1.0.0
  invokerPackage: "Dropbox\\Sign"
  sortModelPropertiesByRequiredFlag: true
  srcBasePath: src
  phpVersion: 7.4
files:
  EventCallbackHelper.mustache:
    templateType: SupportingFiles
    destinationFilename: src/EventCallbackHelper.php
  VERSION.mustache:
    templateType: SupportingFiles
    destinationFilename: VERSION
globalProperties:
  apiTests: false
  modelTests: false
