generatorName: ruby
typeMappings: {}
additionalProperties:
  gemAuthor: Dropbox
  gemAuthorEmail: apisupport@hellosign.com
  gemDescription: Official Dropbox Sign APIv3 OpenAPI Ruby SDK
  gemHomepage: https://hellosign.com
  gemLicense: MIT
  gemName: dropbox-sign
  gemRequiredRubyVersion: '>= 2.7'
  moduleName: "Dropbox::Sign"
  gemVersion: 1.0.0-beta2301
  sortModelPropertiesByRequiredFlag: true
  legacyDiscriminatorBehavior: true
files:
  event_callback_helper.mustache:
    templateType: SupportingFiles
    destinationFilename: lib/dropbox-sign/event_callback_helper.rb
globalProperties:
  apiTests: false
  modelTests: false
