generatorName: ruby
typeMappings: {}
additionalProperties:
  gemAuthor: Dropbox
  gemAuthorEmail: apisupport@hellosign.com
  gemDescription: Official Dropbox Sign APIv3 OpenAPI Ruby SDK
  gemHomepage: https://hellosign.com
  gemLicense: MIT
  gemName: dropbox-sign
  gemRequiredRubyVersion: '>= 2.7'
  moduleName: "Dropbox::Sign"
  gemVersion: 1.4.1
  sortModelPropertiesByRequiredFlag: true
  legacyDiscriminatorBehavior: true
  gitUserId: hellosign
  gitRepoId: dropbox-sign-ruby
files:
  event_callback_helper.mustache:
    templateType: SupportingFiles
    destinationFilename: lib/dropbox-sign/event_callback_helper.rb
  VERSION-root.mustache:
    templateType: SupportingFiles
    destinationFilename: VERSION
globalProperties:
  apiTests: false
  modelTests: false
