generatorName: java
additionalProperties:
  library: jersey2
  openApiNullable: false
  java8: true
  invokerPackage: com.dropbox.sign
  apiPackage: com.dropbox.sign.api
  modelPackage: com.dropbox.sign.model
  developerEmail: apisupport@hellosign.com
  developerName: Dropbox Sign API Team
  developerOrganization: Dropbox Sign
  developerOrganizationUrl: https://hellosign.com
  hideGenerationTimestamp: true
  sortModelPropertiesByRequiredFlag: true
  groupId: com.dropbox.sign
  artifactId: dropbox-sign
  artifactVersion: 1.0.0-beta2301
  artifactUrl: https://github.com/hellosign/dropbox-sign-java
  artifactDescription: Use the Dropbox Sign Java SDK to connect your Java app to Dropbox Sign\'s service in microseconds!
  scmConnection: scm:git:git://github.com/hellosign/dropbox-sign-java.git
  scmDeveloperConnection: scm:git:git@github.com:hellosign/dropbox-sign-java.git
  scmUrl: https://github.com/hellosign/dropbox-sign-java
  licenseName: MIT License

files:
  EventCallbackHelper.mustache:
    templateType: SupportingFiles
    destinationFilename: src/main/java/com/dropbox/sign/EventCallbackHelper.java
globalProperties:
  apiTests: false
  modelTests: false
