generatorName: java
additionalProperties:
  library: jersey2
  openApiNullable: false
  java8: true
  invokerPackage: com.hellosign.openapi
  apiPackage: com.hellosign.openapi.api
  modelPackage: com.hellosign.openapi.model
  developerEmail: apisupport@hellosign.com
  developerName: HelloSign API Team
  developerOrganization: HelloSign
  developerOrganizationUrl: https://hellosign.com
  hideGenerationTimestamp: true
  sortModelPropertiesByRequiredFlag: true
  groupId: com.hellosign
  artifactId: hellosign-java-sdk
  artifactVersion: 6.0.0-beta22.24
  artifactUrl: https://github.com/hellosign/hellosign-java-sdk
  artifactDescription: Use the HelloSign Java SDK to connect your Java app to HelloSign\'s service in microseconds!
  scmConnection: scm:git:git://github.com/hellosign/hellosign-java-sdk.git
  scmDeveloperConnection: scm:git:git@github.com:hellosign/hellosign-java-sdk.git
  scmUrl: https://github.com/hellosign/hellosign-java-sdk
  licenseName: MIT License

files:
  EventCallbackHelper.mustache:
    templateType: SupportingFiles
    destinationFilename: src/main/java/com/hellosign/openapi/EventCallbackHelper.java
globalProperties:
  apiTests: false
  modelTests: false
